### ISSUE TITLE
Unable to complete dotnetbuild

### ISSUE THREAD

**Issue by zbskillable** [MicrosoftLearning/MSLearnLabs-AZ-220-Microsoft-Azure-IoT-Developer#1]
# Module: 06
#### Step: 09

Description of issue
Unable to complete dotnet build, the Program.cs file in the Starter folder is missing the Main method however, the Program.cs file in the Final folder has the missing c# code and is currently a workaround to this issue.

![mainmethod](https://user-images.githubusercontent.com/42649591/156196707-b961b10f-cfcb-4f87-9b7a-414aeb2259da.png)

**Comment by ChrisHowd** [comment]
Thanks for reporting your issue. The lab instructions have been updated.
